### ISSUE TITLE
NoMethodError: undefined method `spec' for nil:NilClass

### ISSUE THREAD

**Issue by sradu** [doorkeeper-gem/doorkeeper-mongodb#14]
Hi

I've started getting the error below when running bundle install. I've been browsing the issues here, and I understand that there's a problem with lack of maintainership, but it would be great if it would still work until we find an alternative.

NoMethodError: undefined method `spec' for nil:NilClass
An error occurred while installing doorkeeper-mongodb (3.0.0), and Bundler cannot continue.
Make sure that`gem install doorkeeper-mongodb -v '3.0.0'` succeeds before bundling.

**Comment by nbulaj** [comment]
Hi @sradu . You can try to update to `Doorkeeper` 4 and use current _master_ of `doorkeeper-mongodb`. If you will face some problems - let me know.
