### ISSUE TITLE
Incompatibility with rails 5(mongoid6) and rails-4.2.6(mongoid5)

### ISSUE THREAD

**Issue by shipdcare** [doorkeeper-gem/doorkeeper-mongodb#16]
Getting an error undefined method `refresh_token_revoked_on_use?' for Doorkeeper::AccessToken:Class

**Comment by tute** [comment]
Unfortunately https://github.com/doorkeeper-gem/doorkeeper-mongodb may be out of date, and has no maintainer.

**Comment by tute** [comment]
I answered in duplicate https://github.com/doorkeeper-gem/doorkeeper-mongodb/issues/18 how to fix. Closing this in favor of that one.
