### ISSUE TITLE
Incompatibility with rails 5 and mongoid 6

### ISSUE THREAD

**Issue by imadmoussa1** [doorkeeper-gem/doorkeeper-mongodb#18]
i am using : 
       'rails', '5.0.0.1'
       mongoid (6.0.0)
       doorkeeper (4.2.0)
       devise **(4.2.0)**

Getting an error :

![sketch](https://cloud.githubusercontent.com/assets/20532475/18306482/b913ef74-74f4-11e6-8aca-63b9fb4e302f.png)

**Comment by syedanabimam** [comment]
Kind of same issue here, it seems mongoid 6.0.0 is not properly supported at this moment :(

**Comment by tute** [comment]
Yeah, you can send a PR similar to https://github.com/doorkeeper-gem/doorkeeper-mongodb/pull/15 to fix it. And you can also maintain this gem that I don't! :)

**Comment by tomascharad** [comment]
Is there any 'clue' on how to start working on this PR?
