### ISSUE TITLE
Please add a CHANGELOG

### ISSUE THREAD

**Issue by gottfrois** [doorkeeper-gem/doorkeeper-mongodb#27]
Hey there,

Would it be possible to maintain a CHANGELOG file so it's easier to follow what changes over time and if there are breaking changes pushed?
For example, I see that rubygems as currently version 4.0.1 but a released seem to have been made for 4.1.0.

It's quite confusing

**Comment by nbulaj** [comment]
Hi @gottfrois . 4.1 version is not released yet, so an actual version is 4.0.1. But you are right and we need CHANGELOG for the project.

**Comment by gottfrois** [comment]
You can also use the Releases tab of github to track changes ;)

**Comment by nbulaj** [comment]
Unfortunately, previous maintainers did not adhere to this approach. But now we can start to do it :)

**Comment by nbulaj** [comment]
Added. Thanks!
