### ISSUE TITLE
NoMethodError: undefined method `polymorphic_resource_owner?' for #<Doorkeeper::Config:0x00007fcd0ef10260>

### ISSUE THREAD

**Issue by artfuldodger** [doorkeeper-gem/doorkeeper-mongodb#43]
### Steps to reproduce

Set up an application to use doorkeeper-mongodb 5.20 and doorkeeper 5.3.1.

### Expected behavior

Applications should work as expected without raising an exception.

### Actual behavior

```
NoMethodError:
       undefined method `polymorphic_resource_owner?' for #<Doorkeeper::Config:0x00007fcd0ef10260>
```

This is due to the fact that `polymorphic_resource_owner?` is not defined on `Doorkeeper::Config` in the latest released version of doorkeeper (5.3.1) but it is on master. Telling bundler to pull the latest doorkeeper from Github fixes the issue, but I would expect to be able to use the latest published versions.

### System configuration
**Ruby version**: 2.6.5

**Comment by nbulaj** [comment]
Doh, thanks @artfuldodger for the report! I know the roots of the issue. I'll fix tomorrow, thanks!

**Comment by nbulaj** [comment]
Hi @artfuldodger . Could you please check if everything OK with the master branch? I merged the fix, but wanna to be sure

**Comment by artfuldodger** [comment]
I tested with the released version of doorkeeper and the master version of doorkeeper-mongodb and everything seemed good to me! Thanks!
