### ISSUE TITLE
support mongoid 5?

### ISSUE THREAD

**Issue by calfzhou** [doorkeeper-gem/doorkeeper-mongodb#7]
Is there any plan to support mongoid5? Though it is still in beta version, but i found that mongoDB's official documentation is saying about mongoid5: http://docs.mongodb.org/ecosystem/tutorial/ruby-mongoid-tutorial/

**Comment by luis-ca** [comment]
+1

**Comment by bartes** [comment]
+1

**Comment by jasl** [comment]
It's support Mongoid 5.0, just keep set `orm :mongoid4`
I've already running on production for two weeks, and I've checked the codes are compatible with Mongoid 5.0

Maybe I would send a PR to clear, but sorry I'm too busy for now.

**Comment by jasl** [comment]
Now it's support Mongoid 5 officially, just checkout the latest commit.
